config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "lists#index"

  resources :lists do
    member do
      post :done
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :name, :due_date, :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, :only => [:show, :edit, :update, :destroy, :done]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_url
    else
      render :action => :new
    end
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to list_path(@list)
    else 
      render :action => :edit
    end  
  end

  def destroy
      @list.destroy
      redirect_to lists_url
  end

  def done
      @list.update(done: !(@list.done))
  end

  private


  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :due_date, :note, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.present? %>
  <ul>
    <% @list.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
<%= form_for @list do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :due_date, "Due Date" %>
    <%= f.text_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :note, "Note" %>
    <%= f.text_area :note, class: "form-control" %>
  </div>
  
  <%= f.submit %>

<% end %>
</div>

app/views/lists/edit.html.erb
<%= render :partial => "form" %>

app/views/lists/index.html.erb
<ul>
  <h1>
    <%="To Do List" %>
  </h1>
  <h2>
    <%= "Today: #{Time.new.to_date}" %>
  </h2>
  <table class="table table-hover">
    <tr>
    <th><%= "Done" %></th>
    <th><%= "Name" %></th>
    <th><%= "Due Date" %></th>
    <th><%= "Show" %></th>
    <th><%= "Edit" %></th>
    <th><%= "Destroy" %></th>
    </tr>
    <% @lists.each do |list| %>
      <tr>
          <td>
            <%= check_box_tag :done, true , list.done, data: { url: done_list_path(list), method: :post, remote: true } %>
          </td>
        <td><%= list.name %></td>
        <td><%= list.due_date %></td>     
        <td><%= link_to 'Show', list_path(list) %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>        
          <% if list.due_date < Time.new.to_date %>
            <td><%= "Overdue" %></td>
          <% else %>
            <td><%= link_to 'Destroy', list_path(list), method: :delete, data:{ confirm: "Are you sure?" } %></td>
          <% end %>
      </tr>
    <% end %>
  </table>

<button type="button" class="btn btn-warning"><%= link_to 'New List', new_list_path %></button>

app/views/lists/new.html.erb
<%= render :partial => "form" %>

app/views/lists/show.html.erb
<table class="table table-condensed table-hover text-center">
<tr><td><h3><%= @list.name %></h3></td></tr>
<tr><td><%= @list.due_date %></td></tr>
<tr><td><%= simple_format(@list.note) %></td></tr>
<tr><td><%= link_to 'Back to index', lists_path %></td></tr>
</table>